# Generated by Django 5.2.7 on 2026-09-11 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0014_alter_quotation_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="reconciled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tender",
            name="reconciled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reconciled_tenders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tender",
            name="reconciliation_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="tender",
            name="reconciliation_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("RECONCILED", "Reconciled"),
                    ("VARIANCE", "Variance"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="tender",
            index=models.Index(
                fields=["reconciliation_status", "tender_type"],
                name="idx_tender_recon_status",
            ),
        ),
    ]
