# Generated by Django 5.2.7 on 2025-10-25 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('db_name', models.CharField(max_length=200)),
                ('db_user', models.CharField(max_length=200)),
                ('db_password', models.CharField(max_length=200)),
                ('db_host', models.CharField(max_length=200)),
                ('db_port', models.IntegerField(default=5432)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant_control', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tenant',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('schema_name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='tenancy.tenant')),
            ],
            options={
                'verbose_name': 'Shop',
            },
        ),
    ]
