# Generated by Django 5.2.7 on 2025-12-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='is_head_office',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='shop',
            constraint=models.UniqueConstraint(condition=models.Q(('is_head_office', True)), fields=('tenant', 'is_head_office'), name='unique_head_office_per_tenant'),
        ),
    ]
