# Generated by Django 5.2.7 on 2025-12-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0002_shop_is_head_office_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='email',
            field=models.EmailField(default='admin@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='tenant',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='db_host',
            field=models.CharField(default='localhost', max_length=200),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='db_password',
            field=models.CharField(default='0660089932@G', max_length=200),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='db_user',
            field=models.CharField(default='postgres', max_length=200),
        ),
    ]
