# Generated by Django 5.2.7 on 2025-12-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0003_tenant_email_tenant_phone_alter_tenant_db_host_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
