# Generated by Django 5.2.7 on 2025-12-29 16:10

import tenancy.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0006_alter_tenant_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='db_password',
            field=tenancy.models.EncryptedCharField(max_length=200),
        ),
    ]
