# Generated by Django 5.2.7 on 2026-01-12 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0007_alter_tenant_db_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='subdomain',
            field=models.CharField(blank=True, help_text="Subdomain for tenant access, e.g., 'tenant1'", max_length=100, null=True, unique=True),
        ),
    ]
