# Generated by Django 5.2.7 on 2026-01-12 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0008_tenant_subdomain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='subdomain',
            field=models.CharField(default='default', help_text="Subdomain for tenant access, e.g., 'tenant1'", max_length=100, unique=True),
        ),
    ]
