# Generated by Django 5.2.7 on 2026-01-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0009_alter_tenant_subdomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='subdomain',
            field=models.CharField(blank=True, help_text="Subdomain for shop access, e.g., 'shop1'", max_length=100, null=True),
        ),
    ]
