# Generated by Django 5.2.7 on 2026-01-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0010_shop_subdomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
