# Generated by Django 5.2.7 on 2026-01-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0011_shop_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='subdomain',
            field=models.CharField(blank=True, default='tenant', help_text="Subdomain for shop access, e.g., 'downtown'", max_length=100),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='shop',
            constraint=models.UniqueConstraint(fields=('tenant', 'subdomain'), name='unique_subdomain_per_tenant'),
        ),
    ]
