# Generated by Django 5.2.7 on 2026-09-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0019_tenant_enable_stock_consolidation"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="setup_error",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Exception message from the last failed provisioning attempt, if any",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="setup_error",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Exception message from the last failed provisioning attempt, if any",
            ),
        ),
    ]
