# Generated by Django 5.2.7 on 2025-12-24 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('expcat', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('expcatname', models.CharField(max_length=50)),
                ('expmtd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('expinvat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('exp1', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('exp2', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('exp3', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('exp4', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('exp5', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('exp6', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('exp7', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('exp8', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('exp9', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('exp10', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('exp11', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('exp12', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('supname', models.CharField(max_length=50)),
                ('supadd1', models.CharField(blank=True, max_length=50)),
                ('supadd2', models.CharField(blank=True, max_length=50)),
                ('supadd3', models.CharField(blank=True, max_length=50)),
                ('suppadd1', models.CharField(blank=True, max_length=50)),
                ('suppadd2', models.CharField(blank=True, max_length=50)),
                ('suppadd3', models.CharField(blank=True, max_length=50)),
                ('suptel', models.CharField(blank=True, max_length=20)),
                ('supfax', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('supcont', models.CharField(blank=True, max_length=50)),
                ('supouracc', models.CharField(blank=True, max_length=20)),
                ('supterms', models.CharField(blank=True, max_length=20)),
                ('supdisc', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('supbalbfwd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('supcrnt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sup30', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sup60', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sup90', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sup120', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sup150', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sup180', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('suppmt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('suppmtdate', models.DateField(blank=True, null=True)),
                ('supurchmtd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('supurchytd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bank', models.CharField(blank=True, max_length=50)),
                ('bankcode', models.CharField(blank=True, max_length=10)),
                ('bankacc', models.CharField(blank=True, max_length=20)),
                ('updstksp', models.BooleanField(default=False)),
                ('acctype', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('detail1', models.CharField(blank=True, max_length=50)),
                ('detail2', models.CharField(blank=True, max_length=50)),
                ('detail3', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('trano', models.CharField(max_length=10)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('invat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('source', models.CharField(max_length=10)),
                ('grnno', models.CharField(blank=True, max_length=10)),
                ('taxind', models.CharField(max_length=10)),
                ('expcat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creditors.expensecategory')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='creditors.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierCreditMaster',
            fields=[
                ('rfcno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('datesent', models.DateField(blank=True, null=True)),
                ('dateretn', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=10)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creditors.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierCreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('val', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('qtyrfc', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('qtycred', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('comment', models.CharField(blank=True, max_length=100)),
                ('purchdate', models.DateField(blank=True, null=True)),
                ('suprefno', models.CharField(blank=True, max_length=20)),
                ('rfc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creditors.suppliercreditmaster')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierOpen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trano', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balancedue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ageflag', models.CharField(max_length=10)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creditors.supplier')),
            ],
            options={
                'unique_together': {('supplier', 'trano')},
            },
        ),
        migrations.CreateModel(
            name='SupplierTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strano', models.CharField(max_length=10)),
                ('stdate', models.DateField()),
                ('sduedate', models.DateField(blank=True, null=True)),
                ('stype', models.CharField(max_length=10)),
                ('stsub', models.CharField(max_length=10)),
                ('stgst', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sttot', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stref', models.CharField(blank=True, max_length=20)),
                ('grnno', models.CharField(blank=True, max_length=10)),
                ('station', models.CharField(blank=True, max_length=10)),
                ('user', models.CharField(blank=True, max_length=20)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creditors.supplier')),
            ],
            options={
                'unique_together': {('supplier', 'strano')},
            },
        ),
    ]
