# Generated by Django 5.2.7 on 2025-12-24 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('quoteno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('expdate', models.DateField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('add1', models.CharField(blank=True, max_length=50)),
                ('add2', models.CharField(blank=True, max_length=50)),
                ('add3', models.CharField(blank=True, max_length=50)),
                ('tel', models.CharField(blank=True, max_length=20)),
                ('comment1', models.CharField(blank=True, max_length=100)),
                ('comment2', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(max_length=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('salesman', models.CharField(blank=True, max_length=20)),
                ('stanum', models.CharField(blank=True, max_length=10)),
                ('dno', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('datemailed', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supname', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=10)),
                ('stockcode', models.CharField(max_length=20)),
                ('descrip', models.CharField(max_length=50)),
                ('unitofmeas', models.CharField(blank=True, max_length=10)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sell1', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sell2', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sell3', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('effectdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sprice', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('disc', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('comments', models.CharField(blank=True, max_length=100)),
                ('dept', models.CharField(blank=True, max_length=10)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('taxind', models.CharField(max_length=10)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase_orders.purchaseorder')),
            ],
        ),
    ]
