# Generated by Django 5.2.7 on 2025-12-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashBookCheque',
            fields=[
                ('cbtrano', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cbref', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cbtag', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CashBookTransaction',
            fields=[
                ('cbtrano', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cbref', models.CharField(max_length=20)),
                ('cbaudit', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('type', models.CharField(max_length=10)),
                ('catno', models.CharField(max_length=10)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cbtag', models.CharField(max_length=10)),
                ('taxind', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CashierShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('invcount', models.IntegerField(default=0)),
                ('invtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cncount', models.IntegerField(default=0)),
                ('cntotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cslcount', models.IntegerField(default=0)),
                ('csltotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cretcount', models.IntegerField(default=0)),
                ('crettotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('arrecount', models.IntegerField(default=0)),
                ('arrectotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('poutcount', models.IntegerField(default=0)),
                ('pouttotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('newlbcount', models.IntegerField(default=0)),
                ('newlbtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lbreccount', models.IntegerField(default=0)),
                ('lbrectotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lbcanccount', models.IntegerField(default=0)),
                ('lbcantotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tend1total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tend1count', models.IntegerField(default=0)),
                ('tend2total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tend2count', models.IntegerField(default=0)),
                ('tend3total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tend3count', models.IntegerField(default=0)),
                ('tend4total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tend4count', models.IntegerField(default=0)),
                ('abancount', models.IntegerField(default=0)),
                ('abantotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('adjust', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('adjcount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('expcat', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('expcatname', models.CharField(max_length=50)),
                ('expmtd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('expinvat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('exp1', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('exp2', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('exp3', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('exp4', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('exp5', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('exp6', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('exp7', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('exp8', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('exp9', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('exp10', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('exp11', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('exp12', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeCategory',
            fields=[
                ('inccat', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('inccatname', models.CharField(max_length=50)),
                ('incmtd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('incinvat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('inc1', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('inc2', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('inc3', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('inc4', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('inc5', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('inc6', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('inc7', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('inc8', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('inc9', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('inc10', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('inc11', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('inc12', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
