# Generated by Django 5.2.7 on 2025-12-08 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_users', '0001_initial'),
        ('tenancy', '0002_shop_is_head_office_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='tenancy.tenant'),
        ),
    ]
