# Generated by Django 5.2.7 on 2025-12-24 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_users', '0001_initial'),
    ]

    operations = [
        # Shop field already added as integer in 0001_initial
    ]
