# Generated by Django 5.2.7 on 2026-01-12 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_users', '0002_shopuser_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='username',
            field=models.CharField(help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True),
        ),
    ]
