# Generated by Django 5.2.7 on 2026-01-12 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_users', '0002_shopuser_shop'),
    ]

    operations = [
        # Username already correct in 0001_initial
    ]
