# Generated by Django 5.2.7 on 2026-01-12 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_users', '0003_alter_shopuser_username'),
    ]

    operations = [
        # Username already correct in 0001_initial
    ]
