# Generated by Django 5.2.7 on 2026-01-16 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_users', '0005_shopuser_remove_fk_use_integers'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='shopuser',
            new_name='shop_users__tenant__f05a04_idx',
            old_name='shop_users_tenant_role_idx',
        ),
        migrations.RenameIndex(
            model_name='shopuser',
            new_name='shop_users__tenant__33aeb2_idx',
            old_name='shop_users_tenant_user_idx',
        ),
    ]
