# Generated by Django 5.2.7 on 2025-12-24 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DebtorArea',
            fields=[
                ('darea', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dareaname', models.CharField(max_length=50)),
                ('arsls1', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('arsls2', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('arsls3', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('arsls4', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('arsls5', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('arsls6', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('arsls7', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('arsls8', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('arsls9', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('arsls10', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('arsls11', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('arsls12', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Debtor',
            fields=[
                ('dno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=50)),
                ('dsname', models.CharField(blank=True, max_length=30)),
                ('dadd1', models.CharField(blank=True, max_length=50)),
                ('dadd2', models.CharField(blank=True, max_length=50)),
                ('dadd3', models.CharField(blank=True, max_length=50)),
                ('dpcode', models.CharField(blank=True, max_length=10)),
                ('dtel', models.CharField(blank=True, max_length=20)),
                ('tel2', models.CharField(blank=True, max_length=20)),
                ('dfax', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('delad1', models.CharField(blank=True, max_length=50)),
                ('delad2', models.CharField(blank=True, max_length=50)),
                ('delad3', models.CharField(blank=True, max_length=50)),
                ('delad4', models.CharField(blank=True, max_length=50)),
                ('dcontact', models.CharField(blank=True, max_length=50)),
                ('dtaxno', models.CharField(blank=True, max_length=20)),
                ('dbalbfwd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dcrnt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('d30', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('d60', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('d90', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('d120', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('d150', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('d180', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dsalesm', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dsalesy', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dprofitm', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dprofity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('damtlpd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ddatlpd', models.DateField(blank=True, null=True)),
                ('ddiscper', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('dclimit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dintflag', models.BooleanField(default=False)),
                ('price', models.CharField(blank=True, max_length=10)),
                ('acctype', models.CharField(blank=True, max_length=10)),
                ('terms', models.CharField(blank=True, max_length=20)),
                ('pdisc', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discprn', models.BooleanField(default=False)),
                ('dposbal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('blockflag', models.BooleanField(default=False)),
                ('dateopened', models.DateField(blank=True, null=True)),
                ('vatref', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('darea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='debtors.debtorarea')),
            ],
        ),
        migrations.CreateModel(
            name='DebtorOpen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtrano', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balancedue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ageflag', models.CharField(max_length=10)),
                ('posted', models.BooleanField(default=False)),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debtors.debtor')),
            ],
            options={
                'unique_together': {('debtor', 'dtrano')},
            },
        ),
        migrations.CreateModel(
            name='DebtorTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtrano', models.CharField(max_length=10)),
                ('dtdate', models.DateField()),
                ('time', models.TimeField()),
                ('dtype', models.CharField(max_length=10)),
                ('dtsub', models.CharField(max_length=10)),
                ('dtgst', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dttot', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dtaxstat', models.CharField(max_length=10)),
                ('source', models.CharField(max_length=10)),
                ('ordno', models.CharField(blank=True, max_length=10)),
                ('custref', models.CharField(blank=True, max_length=20)),
                ('del1', models.CharField(blank=True, max_length=50)),
                ('del2', models.CharField(blank=True, max_length=50)),
                ('del3', models.CharField(blank=True, max_length=50)),
                ('del4', models.CharField(blank=True, max_length=50)),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debtors.debtor')),
            ],
            options={
                'unique_together': {('debtor', 'dtrano')},
            },
        ),
    ]
